# Generated by Django 5.1.1 on 2024-10-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('industry', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Construction', 'Construction'), ('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Information Technology', 'Information Technology'), ('Manufacturing', 'Manufacturing'), ('Retail', 'Retail'), ('Telecommunications', 'Telecommunications'), ('Transportation', 'Transportation'), ('Other', 'Other')], max_length=30)),
                ('date_of_birth', models.DateField()),
                ('product_enquiry', models.CharField(choices=[('Funding and Advisory Services', 'Funding and Advisory Services'), ('Micro Financing', 'Micro Financing'), ('Product Financing', 'Product Financing'), ('Business Strategy Advisory', 'Business Strategy Advisory')], max_length=30)),
                ('comments', models.TextField()),
            ],
        ),
    ]
