# Generated by Django 5.1.1 on 2024-10-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='industry',
            field=models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Construction', 'Construction'), ('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Information Technology', 'Information Technology'), ('Manufacturing', 'Manufacturing'), ('Retail', 'Retail'), ('Telecommunications', 'Telecommunications'), ('Transportation', 'Transportation'), ('Other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='product_enquiry',
            field=models.CharField(blank=True, choices=[('Funding and Advisory Services', 'Funding and Advisory Services'), ('Micro Financing', 'Micro Financing'), ('Product Financing', 'Product Financing'), ('Business Strategy Advisory', 'Business Strategy Advisory')], max_length=30, null=True),
        ),
    ]
